import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'


const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
      <h1>my-note</h1>
      </header>
      <main className={styles.main}>
       <ul>
         <li>aaaa</li>
         <li>ssss</li>
         <li>dddd</li>
         <li>ffff</li>
         <li>bbbbb</li>
       </ul>
      </main>

      <footer className={styles.footer}>
        <p>footer</p>
      </footer>
    </div>
  )
}

export default Home
