import type { NextPage } from 'next'
import Head from 'next/head'
import ItemList from './../src/ui/itemList'
import Image from 'next/image'
import styles from '../styles/Home.module.css'


const Home: NextPage = () => {
const items = ["HTML/CSS", "JavaScriptについて", "React", "Swift", "WebAPI"]

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
      <h1>my-note</h1>
      </header>
      <main className={styles.main}>
        {<ItemList items={items}/>}
      </main>

      <footer className={styles.footer}>
        <p>footer</p>
      </footer>
    </div>
  )
}

export default Home
